# Generated by Django 4.2.1 on 2023-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
