# Generated by Django 4.2.1 on 2023-05-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sub_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='starting_bid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
